server {
    listen 80;
    server_name your_domain.com

    # NEXT.JS APP
    location / {
        proxy_pass http://app:3000;
    }

    # MINIO S3
    location /s3/ {
        rewrite ^/s3/(.*)$ /$1 break;
        proxy_pass http://minio:9000;
    }
}